-- Create a new database
CREATE DATABASE individuella2;

-- Create the 'users' table
CREATE TABLE users (
                       userid         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username       TEXT NOT NULL,
                       hashedpassword TEXT NOT NULL
);

-- Assign ownership (optional)
ALTER TABLE users OWNER TO postgres;

-- Create the 'transactions' table
CREATE TABLE transactions (
                              transactionid   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              userid          INTEGER NOT NULL
                                  CONSTRAINT transactions_users_fk
                                      REFERENCES public.users
                                      ON DELETE CASCADE,
                              amount          NUMERIC NOT NULL,
                              transactiondate TIMESTAMP NOT NULL,
                              description     TEXT
);

-- Assign ownership (optional)
ALTER TABLE transactions OWNER TO postgres;
